export const RRC_NOTIFY_OPEN = 'RRC_NOTIFY_OPEN';
export const RRC_NOTIFY_CLOSE = 'RRC_NOTIFY_CLOSE';
export const RRC_NOTIFY_DESTROY = 'RRC_NOTIFY_DESTROY';
export const RRC_NOTIFY_CLOSE_ALL = 'RRC_NOTIFY_CLOSE_ALL';
